package com.relaunchher.spring_boot_with_react.dao.model;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import java.util.Objects;

@Entity
@Table(name="user_info")
public class User {
//  id | name     | user_name | password    | gender | age  | email
  @Id
  // auto generated by database
  @GeneratedValue(strategy = GenerationType.IDENTITY)
  private long id;

  @Column(name="name")
  private String name;

  @Column(name="user_name")
  private String username;

  @Column(name="password")
  private String password;

  @Column(name="email")
  private String email;

  @Column(name="age")
  private int age;

  @Column(name="gender")
  private String gender;

  public long getId() {
    return id;
  }

  public String getName() {
    return name;
  }

  public String getUsername() {
    return username;
  }

  public String getEmail() {
    return email;
  }

  public int getAge() {
    return age;
  }

  public String getGender() {
    return gender;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    User user = (User) o;
    return id == user.id && age == user.age && Objects.equals(name, user.name)
        && Objects.equals(username, user.username) && Objects.equals(password,
        user.password) && Objects.equals(email, user.email) && Objects.equals(
        gender, user.gender);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, username, password, email, age, gender);
  }

  @Override
  public String toString() {
    return "User{" +
        "id=" + id +
        ", name='" + name + '\'' +
        ", username='" + username + '\'' +
        ", password='" + password + '\'' +
        ", email='" + email + '\'' +
        ", age=" + age +
        ", gender='" + gender + '\'' +
        '}';
  }
}
